FROM maven:3.8-openjdk-17 as builder
WORKDIR /usr/src/url-shortener
COPY ./url-shortener/pom.xml .
RUN mvn -B dependency:go-offline
COPY ./url-shortener .

# we don't need tests when building an image, especially since we have repository tests that connect to DB

RUN mvn clean package -DskipTests=true

FROM amazoncorretto:17-alpine-jdk
COPY --from=builder /usr/src/url-shortener/target/url-shortener-0.0.1-SNAPSHOT.jar url-shortener-0.0.1.jar
EXPOSE 8081
ENTRYPOINT ["java","-jar", "-Dspring.profiles.active=prod","url-shortener-0.0.1.jar"]
