version: "3.7"
services:
  db:
    container_name: postgres
    image: postgres:13.0
    environment:
      POSTGRES_USER: url-shortener
      # it's always safer to have secrets in their own file
      POSTGRES_PASSWORD: UrLSh00RT3NER
      POSTGRES_DB: url-shortener
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
      # - ./db:/docker-entrypoint-initdb.d
    ports:
      - "5460:5432"
    networks:
      - postgres
    restart: unless-stopped

  # if you want pgadmin to pull down the DB client
  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
  #     PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
  #     PGADMIN_CONFIG_SERVER_MODE: "False"
  #   volumes:
  #     - pgadmin:/var/lib/pgadmin
  #   ports:
  #     - "5050:80"
  #   networks:
  #     - postgres
  #   restart: unless-stopped

  url-checker:
    image: ${GROUP_ID}/url-checker:1.0
    volumes:
      - .:/usr/src/url-checker/
    ports:
      - 9095:9095
    networks:
      - ${GLOBAL_NETWORK:-services}

  url-shortener:
    image: ${GROUP_ID}/url-shortener:1.0
    ports:
      - "8081:8081"
    volumes:
      - "./docker-logs:/workspace/url-shortener/logs" # logs are not produced
      - "./check-url-checker-upa.sh:/usr/local/bin/check-url-checker-upa.sh"
    user: root
    # or make it executable
    # entrypoint: ["sh", "check-url-checker-upa.sh"]
    depends_on: # depends on just specify the order, it doesn't do the healthcheck
      - db
      - url-checker

    environment:
      - "JAVA_OPTS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5006 -Xms128m -Xmx256m"
      - "LOGGING_LEVEL_COM_MICROSERVICES_DEMO=info"
      - "LOGGING_LEVEL_ROOT=info"

    networks:
      - ${GLOBAL_NETWORK:-services}
      - postgres

  url-shortener-frontend:
    image: ${GROUP_ID}/url-shortener-frontend:1.0
    ports:
      - "3000:3000"

    depends_on: # depends_on just specify the order, it doesn't do the healthcheck
      - db
      - url-checker
      - url-shortener
    networks:
      - ${GLOBAL_NETWORK:-services}

networks:
  postgres:
    driver: bridge
  url-shortener:
    driver: bridge

volumes:
  postgres:
  pgadmin:
