# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# Name[optional] - displayed on repos action page
name: url-shortener service CI

on: # required
  # every time the push to url-branch is triggered, this workflow should be executed
  push:
  #   branches: [$default-branch]
  # # every time the PR to url-branch is triggered, this workflow should be executed
  pull_request:
  #   branches: [$default-branch]
  # The list of events - https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows

jobs: # required
  # one or more jobs
  url-shortener-build: # jobs.build
    # trigger this job only if the source branch is url-shortener or the main branch itself
    if: ${{ github.ref == 'refs/heads/url-shortener' || github.ref == 'refs/heads/main' || github.head_ref == 'url-shortener' || github.head_ref == 'main' }}
    # The operating system installed on the CI/CD workflow runner
    # runs-on: ubuntu-latest # Ubuntu, Windows and macOS
    runs-on: ${{matrix.os}} # Ubuntu, Windows and macOS
    strategy:
      matrix:
        os: [ubuntu-latest, window-latest, macOS-latest]
    # sequence of tasks/steps
    steps:
      # 1. Set up JDK 17
      # 2. Build with Maven
      # based on predefined checkout action - https://github.com/actions/checkout/tree/v3/; use `uses` expression
      - uses: actions/checkout@v3
      # name of the step
      - name: Set up JDK 17
        # https://github.com/actions/setup-java/tree/v3/; downloads and sets up the wanted version of Java
        uses: actions/setup-java@v3
        with:
          # uses Java 17
          java-version: "17"
          # based on temurin version of Java - https://adoptium.net/temurin/releases/
          distribution: "temurin"
          # cache Maven dependencies between builds
          cache: maven
      - name: Build with Maven
        # package the artifact in non-interactive mode based on POM file
        run: mvn -B package --file url-shortener/pom.xml
  # The way to make jobs dependent
  # publish:
  #   needs: build
